[2023-09-15T10:20:26.232+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cinlok3.insert_into_songs manual__2023-09-15T10:15:15.248626+00:00 [queued]>
[2023-09-15T10:20:26.468+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cinlok3.insert_into_songs manual__2023-09-15T10:15:15.248626+00:00 [queued]>
[2023-09-15T10:20:26.469+0000] {taskinstance.py:1331} INFO - Starting attempt 2 of 2
[2023-09-15T10:20:26.506+0000] {taskinstance.py:1350} INFO - Executing <Task(GenericTransfer): insert_into_songs> on 2023-09-15 10:15:15.248626+00:00
[2023-09-15T10:20:26.520+0000] {standard_task_runner.py:57} INFO - Started process 2905 to run task
[2023-09-15T10:20:26.531+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'cinlok3', 'insert_into_songs', 'manual__2023-09-15T10:15:15.248626+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/songs.py', '--cfg-path', '/tmp/tmpv9c8fze_']
[2023-09-15T10:20:26.536+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask insert_into_songs
[2023-09-15T10:20:26.656+0000] {task_command.py:410} INFO - Running <TaskInstance: cinlok3.insert_into_songs manual__2023-09-15T10:15:15.248626+00:00 [running]> on host 808631ad8fb6
[2023-09-15T10:20:26.860+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Aldinoharyo' AIRFLOW_CTX_DAG_ID='cinlok3' AIRFLOW_CTX_TASK_ID='insert_into_songs' AIRFLOW_CTX_EXECUTION_DATE='2023-09-15T10:15:15.248626+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-15T10:15:15.248626+00:00'
[2023-09-15T10:20:26.906+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/generic_transfer.py", line 74, in execute
    source_hook = BaseHook.get_hook(self.source_conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 84, in get_hook
    connection = cls.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 434, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres` isn't defined
[2023-09-15T10:20:26.916+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=cinlok3, task_id=insert_into_songs, execution_date=20230915T101515, start_date=20230915T102026, end_date=20230915T102026
[2023-09-15T10:20:26.942+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 16 for task insert_into_songs (The conn_id `postgres` isn't defined; 2905)
[2023-09-15T10:20:26.983+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-09-15T10:20:27.025+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
