[2023-09-15T10:38:10.477+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cinlok2.insert_into_artist_revenue manual__2023-09-15T10:32:58.656083+00:00 [queued]>
[2023-09-15T10:38:10.498+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cinlok2.insert_into_artist_revenue manual__2023-09-15T10:32:58.656083+00:00 [queued]>
[2023-09-15T10:38:10.500+0000] {taskinstance.py:1331} INFO - Starting attempt 2 of 2
[2023-09-15T10:38:10.550+0000] {taskinstance.py:1350} INFO - Executing <Task(GenericTransfer): insert_into_artist_revenue> on 2023-09-15 10:32:58.656083+00:00
[2023-09-15T10:38:10.563+0000] {standard_task_runner.py:57} INFO - Started process 92 to run task
[2023-09-15T10:38:10.573+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'cinlok2', 'insert_into_artist_revenue', 'manual__2023-09-15T10:32:58.656083+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/revenue.py', '--cfg-path', '/tmp/tmpg1ap6xpe']
[2023-09-15T10:38:10.578+0000] {standard_task_runner.py:85} INFO - Job 24: Subtask insert_into_artist_revenue
[2023-09-15T10:38:10.688+0000] {task_command.py:410} INFO - Running <TaskInstance: cinlok2.insert_into_artist_revenue manual__2023-09-15T10:32:58.656083+00:00 [running]> on host a02d279ed278
[2023-09-15T10:38:10.883+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Aldinoharyo' AIRFLOW_CTX_DAG_ID='cinlok2' AIRFLOW_CTX_TASK_ID='insert_into_artist_revenue' AIRFLOW_CTX_EXECUTION_DATE='2023-09-15T10:32:58.656083+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-15T10:32:58.656083+00:00'
[2023-09-15T10:38:10.929+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/generic_transfer.py", line 74, in execute
    source_hook = BaseHook.get_hook(self.source_conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 84, in get_hook
    connection = cls.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 434, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres` isn't defined
[2023-09-15T10:38:10.947+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=cinlok2, task_id=insert_into_artist_revenue, execution_date=20230915T103258, start_date=20230915T103810, end_date=20230915T103810
[2023-09-15T10:38:10.981+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 24 for task insert_into_artist_revenue (The conn_id `postgres` isn't defined; 92)
[2023-09-15T10:38:11.028+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-09-15T10:38:11.061+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
